; Note : ce fichier est marqué comme "Copy to Output Directory" dans Visual Studio

[General]
; Port sur lequel le serveur de persistance va démarrer
port = 3457
; DMS = système de gestion de données. Valeurs acceptables : mysql ou sqlite
; Ceci est utilisé uniquement en Release.
; Une configuration de solution Debug va écraser cette valeur (notamment les configs Debug-Sqlite et Debug-Mysql)
dms = sqlite
; L'IP de la machine sur laquelle ce programme s'exécute
; Cette adresse est utilisée uniquement dans les builds RELEASE. Dans les builds DEBUG, on suppose 127.0.0.1
; Mettez uniquement une IP ici, pas de noms de domaine
; Note : si vous prévoyez d'effectuer des tests sur un réseau domestique constitué de plusieurs PCs, lisez le paragraphe de documentation "FAQ : tests sur réseau domestique"
PersistenceServerIP = 127.0.0.1
; ServerPassword doit être identique à celui dans GameModeBaseCpp.h
; Ceci est utilisé par les serveurs de jeu pour se connecter au serveur de Persistance
ServerPassword = $2a$12$TVJguxncMvNQS47S5jWw3exf.89gOM43q9omQt58cS1mfn6MrWg8.
; UniversalCookie doit être identique à celui dans GameInstanceCpp.h
; Ceci est utilisé par les clients PIE pour se connecter au serveur de Persistance. Fonctionne uniquement dans les configs DEBUG.
UniversalCookie = $2a$12$ERfi15WDwiTF0dI0WRQrUurrt50zDYoqpHCHixCTUw2WCEh3ZzuM6
; Rang de guilde par défaut qu'un nouvel invité reçoit. Ça devrait être la valeur la plus élevée possible de votre enum EGuildRanks dans UE5
; Par défaut, nous avons 4 rangs : 0 est GM, 1 est Officier, 2 est Membre, 3 est Recrue. Donc par défaut, un membre nouvellement accepté sera 3 = Recrue.
; Recrue est le rang le plus bas. On ne peut pas rétrograder plus bas que DefaultGuildRank
DefaultGuildRank = 3
GuildOfficerRank = 1
PartyMaxSize = 5
[Steam]
; Mettez votre clé WebApi d'éditeur Steam ici - pour l'obtenir, voir la documentation
SteamPublisherKey = 
; Votre Steam App Id
SteamDevAppId = 480
[MySQL]
; 99% du temps votre base de données sera sur le même serveur où se trouve votre serveur de Persistance, donc l'hôte restera localhost
host = localhost
port = 3306
user = root
password = root
; Nom de la base de données. Si aucune BDD avec ce nom n'est détectée, elle sera créée pour vous. Ne la créez pas manuellement, nous devons la peupler.
database = Elyndor
; Quand aucune base de données n'est détectée, le serveur de persistance va créer une base de données pour vous avec une certaine collation.
; La collation déterminera si elle est sensible aux accents ou non.
; Une collation sensible aux accents permettra à vos joueurs d'avoir des personnages distincts avec des accents différents, ex : Laureline et Lauréline
; Une collation insensible aux accents permettra à vos joueurs d'en avoir seulement un, ex : Lauréline
; Le paramètre devient non pertinent après la création de la base de données.
accentSensitiveCollation = true
[Sqlite]
; Une base de données avec ce nom sera créée dans le répertoire où l'exécutable est lancé
; Attention, quand vous changez votre config de Debug à Release, la BDD ne migrera pas automatiquement d'un dossier à l'autre.
; Si vous voulez préserver les données, copiez le fichier de bin\Debug-Sqlite\net6.0 vers bin\Release\net6.0
filename = mmokit.db